---
- hosts: local
  vars:
   - docroot: /var/www/serversforhackers.com/public
  tasks:
   - name: Install Apache2
     apt: pkg=apache2 state=installed update_cache=true
     register: apache2installed
     notify:
      - Start Apache2

   - name: Create Web Root
     when: apache2installed|success
     file: dest={{ docroot }} mode=775 state=directory owner=root group=root
     register:webrootcreated
     notify:
      - Reload Apache2
	  
   - name: Install Git
     apt: pkg=git state=installed update_cache=true
     register: gitinstalled	  
	  
   - name: Deploy code from GitHub
     when: gitinstalled|success
     git: repo=https://github.com/rakesh635/testphp.git dest={{ docroot }} version=HEAD 
	 
   - name: apache2 virtualhost on port 8081
     lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^DocumentRoot /var/www/html" line="DocumentRoot {{ docroot }}" state=present
     notify:
        - Reload Apache2

  handlers:
   - name: Start Apache2
     service: name=apache2 state=started

   - name: Reload Apache2
     service: name=apache2 state=reloaded
